version: "3.4"

services:
  mongo:
    image: mongo:3.6.23
    restart: always
    environment:
      MONGO_INITDB_DATABASE: karma
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: kwangya
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1

volumes:
  mongo-data: {}
