apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: {{ .Values.mongodb.storageSize }}
  storageClassName: {{ .Values.mongodb.storageClassName }}