apiVersion: v1
kind: Secret
metadata:
  name: mongo-creds
  namespace: {{ .Release.Namespace }}
data:
  password: {{ .Values.mongodb.password | b64enc }}
  username: {{ .Values.mongodb.username | b64enc }}