apiVersion: v1
kind: Service
metadata:
  name: slack-ae-bot
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    app: slack-ae-bot