apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: slack-ae-bot
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
  - mesh
  - slack-ae-bot
  hosts:
  -  {{ .Values.externalDomainURL }}
  - slack-ae-bot.{{ .Release.Namespace }}.svc.{{ .Values.clusterName }}
  http:
    - match:
      - port: 80
        uri:
          prefix: /
      route:
        - destination:
            host: slack-ae-bot
            port:
              number: 3000